# Generated by Django 5.0.3 on 2024-05-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('accno', models.CharField(max_length=50)),
                ('cust_state', models.CharField(max_length=100)),
                ('cust_pin', models.CharField(max_length=10)),
                ('dpd', models.IntegerField()),
            ],
        ),
    ]
