# Generated by Django 5.0.3 on 2024-05-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecord',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
